# === Configuração do Worker Cloudflare ===
name = "xcam-api"
main = "index.js"
compatibility_date = "2024-05-01"
workers_dev = true
route = ""
account_id = "b8e7693b1a87d22cdb090eef31e63dc5"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]

enabled = true
